import { motion } from "framer-motion";
import { Upload, Cpu, MessageSquare } from "lucide-react";

const steps = [
  {
    icon: Upload,
    title: "Upload Resume & Job Description",
    description: "Share your resume and the job you're targeting. Our AI tailors questions specifically for your role.",
  },
  {
    icon: Cpu,
    title: "AI Generates Interview Questions",
    description: "Get realistic, role-specific questions generated by AI based on your profile and the job requirements.",
  },
  {
    icon: MessageSquare,
    title: "Take Mock Interview & Get Feedback",
    description: "Answer questions via voice or text and receive detailed, actionable feedback with a performance score.",
  },
];

const HowItWorks = () => {
  return (
    <section id="how-it-works" className="py-24">
      <div className="container">
        <motion.div
          className="text-center mb-16"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <h2 className="text-3xl md:text-4xl font-bold tracking-tight mb-4">
            How It Works
          </h2>
          <p className="text-muted-foreground max-w-lg mx-auto">
            Three simple steps to ace your next interview.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-3 gap-6">
          {steps.map((step, i) => (
            <motion.div
              key={step.title}
              className="group relative rounded-2xl border bg-card p-8 shadow-card hover:shadow-card-hover hover:-translate-y-1 transition-all duration-300"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.1 }}
            >
              <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-primary/10 text-primary mb-5 group-hover:bg-gradient-primary group-hover:text-primary-foreground transition-all duration-300">
                <step.icon className="h-5 w-5" />
              </div>
              <span className="text-xs font-medium text-muted-foreground mb-2 block">
                Step {i + 1}
              </span>
              <h3 className="text-lg font-semibold mb-2">{step.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {step.description}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default HowItWorks;
